name: kwctl release
on:
  push:
    tags:
      - 'v*'
jobs:
  test-windows:
    name: Windows test
    runs-on: windows-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - uses: sigstore/cosign-installer@main
      - run: cosign version
